name: "Build & Test"

on:
  pull_request:
    branches: 
      - main

jobs:
    build:
        name: Call Azure Build+Test Pipeline
        runs-on: ubuntu-latest
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/projectmonai/monai-label
            azure-pipeline-name: 'Build+Test'
            azure-devops-token: ${{ secrets.MONAI_LABEL_AZURE_TOKEN }}
